#!/usr/bin/env perl

use v5.20;

#
# Useage: ./ftp-access-count <month> <year>
#

#
# config
#
my $log_path = "/var/log/nginx/mirrors-access.log*";
my $mirror_path = "/home/docker/mirror/mirrors";
my $tmp_dir = "/tmp";
my $title_text = "软件源使用统计";
my $description = "mirror utilization report, based on ftp access count";
my $end_mday = 10;

#
# get current time
#
my ($sec, $min, $hour, $mday, $mon, $year) = localtime(time);
my @month= qw( Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec );

#
# set post date
#
my $date = sprintf('%04d-%02d-%02d %02d:%02d:%02d +0800',
		$year + 1900, $mon + 1, $mday, $hour, $min, $sec);

#
# query month year
#
my ($qmon, $qm, $qy);
$qmon = $ARGV[0] or $qmon = $mon + 1;
$qy = $ARGV[1] or $qy = $year + 1900;
$qm = $month[$qmon - 1];

#
# set post title, description
#
my $title = "\"[$qm $qy] $title_text\"";

#
# search logfiles and entries
#
my $start_date = sprintf("%04d-%02d-%02d", $qy, $qmon, 1);
my $end_date = sprintf("%04d-%02d-%02d", $qy + $qmon / 12, $qmon % 12 + 1, $end_mday);

chomp (my $start_file = `mktemp $tmp_dir/start.XXXXXXXX`);
chomp (my $end_file = `mktemp $tmp_dir/end.XXXXXXXX`);

`touch --date "$start_date" $start_file`;
`touch --date "$end_date" $end_file`;

chomp(my @logfiles = `find $log_path -type f -newer $start_file -not -newer $end_file`);

`rm $start_file`;
`rm $end_file`;

chomp(my @entries = `ls $mirror_path`);

#
# define success and fail states
# seperated with |
#
my $succ = "200|304";
my $fail = "404";

#
# start ftp access count
#
my %data;

for (@logfiles) {
	if (/\.gz$/) {
		open(INPUT, "-|", "sudo gunzip -c $_");
	} else {
		open(INPUT, "-|", "sudo cat $_");
	}

	LINE: for (<INPUT>) {

	# log example:
	#
	# 10.170.26.173 - - [26/Dec/2016:19:36:44 +0800]\
	# "GET /archlinux/core/os/x86_64/core.db HTTP/1.1" 200 125714\
	# "-" "pacman/5.0.1 (Linux x86_64) libalpm/10.0.1"
	#
		if (m%\[\d+?/$qm/$qy.+\] "GET (\S+?) \S+?" ($succ|$fail)%o) {
			my ($filepath, $state) = ($1, $2);

			# skip directories
			# and must include a entry name
			next LINE unless $filepath =~ m%^/(.+?)/.+[^/]$%;
			my $entry = $1;
			my $stateno = ($state =~ /$fail/o);

			$data{$entry}[$stateno]++;
		}
	}

	close(INPUT);
}

#
# write out the post
#
say "---";
say "layout: post";
say "title: $title";
say "date: $date";
say "categories: reports";
say "description: $description";
say "---";

#@entries = sort keys %data;

say "```";
printf "%-18s %10s %10s\n", "ENTRY", "SUCCESS", "ERR=$fail";
for (@entries) {
	printf "%-18s %10d %10d\n", $_, $data{$_}[0], $data{$_}[1];
}
say "```";

